[project]
name = "bookingapp"
version = "0.1.0"
description = "Booking App"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "djangorestframework>=3.16.1",
    "psycopg2-binary",
    "python-dotenv",
]

[build-system]
requires = ["uv"]
build-backend = "uv"